### ISSUE TITLE
Z-index DatePicker not correct

### ISSUE THREAD

**Issue by rolandoldengarm** [OfficeDev/Office-UI-Fabric#143]
http://plnkr.co/edit/auBR88k6T9dGKocKoGQC?p=preview

When the date/time picker expands, it is transparent which is incorrect.

Can be fixed with this CSS:
.ms-DatePicker-picker {
    z-index: 100 !important;
}

**Comment by casvaniersel** [comment]
Hi rolandoldengarm this is already fixed in PR #111 which is still in the DEV branch I think. This will be merged to master soon I hope.

**Comment by rolandoldengarm** [comment]
Bedankt :)

**Comment by Jahnp** [comment]
Thanks for catching this @rolandoldengarm and for the fix @casvaniersel ! Indeed, the `develop` branch will be merged into `master` shortly--most likely tomorrow--and a new release with the fix should be available later this week or early next week at the latest.

**Comment by Geraint87** [comment]
I have updated to the latest version of Office Fabric from Nuget (v2.6.1), and I am still getting this error with date pickers.

I see the fix has been merged to master, but why isn't it working?

The second date picker appearing in front of the selection frame (Chrome, IE, Firefox):
![image](https://cloud.githubusercontent.com/assets/5928208/16837136/49dc4b3a-49b9-11e6-8ba2-85830b2e7810.png)

(Excel add-in)
![image](https://cloud.githubusercontent.com/assets/5928208/16837297/5aa00d20-49ba-11e6-8dfd-2c71f406412d.png)
